"""
This type stub file was generated by pyright.
"""

from asyncio.events import AbstractEventLoop
from collections.abc import Callable, Coroutine
from typing import Any

"""Asyncio utilities."""
_LOGGER = ...
_SHUTDOWN_RUN_CALLBACK_THREADSAFE = ...
T = ...

def fire_coroutine_threadsafe(coro: Coroutine, loop: AbstractEventLoop) -> None:
    """Submit a coroutine object to a given event loop.

    This method does not provide a way to retrieve the result and
    is intended for fire-and-forget use. This reduces the
    work involved to fire the function on the loop.
    """
    ...

def run_callback_threadsafe(
    loop: AbstractEventLoop, callback: Callable[..., T], *args: Any
) -> concurrent.futures.Future[T]:
    """Submit a callback object to a given event loop.

    Return a concurrent.futures.Future to access the result.
    """
    ...

def check_loop() -> None:
    """Warn if called inside the event loop."""
    ...

def protect_loop(func: Callable) -> Callable:
    """Protect function from running in event loop."""
    ...

async def gather_with_concurrency(
    limit: int, *tasks: Any, return_exceptions: bool = ...
) -> Any:
    """Wrap asyncio.gather to limit the number of concurrent tasks.

    From: https://stackoverflow.com/a/61478547/9127614
    """
    ...

def shutdown_run_callback_threadsafe(loop: AbstractEventLoop) -> None:
    """Call when run_callback_threadsafe should prevent creating new futures.

    We must finish all callbacks before the executor is shutdown
    or we can end up in a deadlock state where:

    `executor.result()` is waiting for its `._condition`
    and the executor shutdown is trying to `.join()` the
    executor thread.

    This function is considered irreversible and should only ever
    be called when Home Assistant is going to shutdown and
    python is going to exit.
    """
    ...
